[workspace]
members = ["crates/protocol"]
# Only check / build main crates by default (check all with `--workspace`)
default-members = ["crates/protocol"]
# exclude = []
resolver = "2"

[workspace.dependencies]
